# Generated by Django 5.1.4 on 2026-02-27 16:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Device ID can only contain letters, numbers, hyphens and underscores.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('idle', 'Idle')], db_index=True, default='offline', max_length=10),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='devices_dev_user_id_2c8247_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-created_at'], name='devices_dev_created_53fbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-last_seen'], name='devices_dev_last_se_0f47ef_idx'),
        ),
    ]
