# Generated by Django 5.1.4 on 2026-02-27 16:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'json', 'xml', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', 'tar', 'gz', 'mp4', 'mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='mimetype',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', '-uploaded_at'], name='files_uploa_user_id_125f44_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['mimetype'], name='files_uploa_mimetyp_3c1fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['-uploaded_at'], name='files_uploa_uploade_5ad9a9_idx'),
        ),
    ]
